### ISSUE TITLE
Music - Volume (Does not scale properly)

### ISSUE THREAD

**Issue by jjplay175** [jjplay175/UnityBot#3]
I have found a few problems with volume and have decided to disable it for now
1. The volume does not scale properly! it seems it is going louder than intended? if you put "-volume 100" it will go to 100% but if you do "-volume 100" the bot will get substantially louder
2. If the bot goes to 100% it gets stuck and it won't let you change the volume, it only gets louder

**Comment by FireCode20** [comment]
Ok will work on the fix, it was always a bit finicky.

**Comment by jjplay175** [comment]
I managed to get it fixed up! I know you have been busy!

your base code really helped a lot with getting it to work, thanks.
